apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: casskube
  namespace: ""
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - casskube
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - khulnasoft.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - '*'
- apiGroups:
  - cassandra.khulnasoft.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
    - batch
  resources:
    - '*'
  verbs:
    - '*'

