kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: casskube
  namespace: ""
subjects:
- kind: ServiceAccount
  name: casskube
roleRef:
  kind: Role
  name: casskube
  apiGroup: rbac.authorization.k8s.io
