apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
spec:
  replicas: {{ .Values.deploymentReplicas }}
  selector:
    matchLabels:
      name: casskube
  template:
    metadata:
      labels:
        name: casskube
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- $imagePullSecrets := list -}}
      {{- if .Values.imagePullSecret }}
        {{- $imagePullSecrets = append $imagePullSecrets .Values.imagePullSecret }}
      {{- end }}
      {{- if .Values.registryUsername }}
        {{- $imagePullSecrets = append $imagePullSecrets "casskube-registry-override-regcred" }}
      {{- end }}
      {{- if empty $imagePullSecrets | not }}
      imagePullSecrets:
      {{- range $imagePullSecrets }}
       - name: {{ . | quote }}
      {{- end }}
      {{- end }}
      volumes:
      - name: tmpconfig-volume
        emptyDir:
           medium: "Memory"
      - name: casskube-certs-volume
        secret:
          secretName: casskube-webhook-config
      containers:
      - name: casskube
        {{- if .Values.image }}
        image: {{ .Values.image }}
        {{- else if .Values.registryName }}
        image: {{ printf "%s/%s" .Values.registryName .Values.defaultImage }}
        {{- else }}
        image: {{ .Values.defaultImage }}
        {{- end }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: casskube-certs-volume
          readOnly: false
        - mountPath: /tmp/
          name: tmpconfig-volume
          readOnly: false
        securityContext:
          runAsUser: 65534
          runAsGroup: 65534
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        livenessProbe:
          exec:
            command:
            - pgrep
            - ".*operator"
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - stat
            - "/tmp/operator-sdk-ready"
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 1
        env:
        {{- if .Values.vmwarePSPEnabled }}
        - name: ENABLE_VMWARE_PSP
          value: "true"
        {{- end }}
        {{- if .Values.registryName }}
        - name: DEFAULT_CONTAINER_REGISTRY_OVERRIDE
          value: {{ .Values.registryName }}
        {{- end }}
        {{- if .Values.registryUsername }}
        - name: DEFAULT_CONTAINER_REGISTRY_OVERRIDE_PULL_SECRETS
          value: casskube-registry-override-regcred
        {{- end }}
        {{- if .Values.clusterWideInstall }}
        - name: WATCH_NAMESPACE
          value: ""
        {{- else }}
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- end }}
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "casskube"
        - name: SKIP_VALIDATING_WEBHOOK
          value: "FALSE"
