apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: "cassandradatacenter-webhook-registration"
webhooks:
- name: "cassandradatacenter-webhook.cassandra.khulnasoft.com"
  rules:
  - apiGroups: ["cassandra.khulnasoft.com"]
    apiVersions: ["v1beta1"]
    operations: ["CREATE", "UPDATE"]
    resources: ["cassandradatacenters"]
    scope: "*"
  clientConfig:
    service:
      name: "cassandradatacenter-webhook-service"
      namespace: {{ .Release.Namespace }}
      path: /validate-cassandra-khulnasoft-com-v1beta1-cassandradatacenter
  admissionReviewVersions: ["v1beta1"]
  timeoutSeconds: 10
  failurePolicy: "Ignore"
  matchPolicy: "Equivalent"
  sideEffects: None
